apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisbrige
  labels:
    app: redisbrige
spec:
  selector:
    matchLabels:
      app: redisbrige
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: redisbrige
    spec:
      containers:
      - name: redisbrige-container
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---

apiVersion: v1
kind: Service
metadata:
  name: redisbrige-service
  labels:
    app: redisbrige
spec:
  ports:
  - port: 6380
    targetPort: 6379
  selector:
    app: redisbrige